config/routes.rb
Rails.application.routes.draw do
  get 'slo/front'
  post 'slo/back'
  get 'sso/auth', as: :sso_auth
  get 'main/welcome'
  root to: "main#welcome"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def welcome
    @logged_in = session[:uid] ? true: false
    @cn = session[:cn]
  end
end

app/controllers/slo_controller.rb
class SloController < ApplicationController
  skip_before_action :verify_authenticity_token, :only => [:back]

  def front
    logger.info("params: #{params}")
    logger.info("session id: #{session.id}")
    session.destroy
    redirect_to(params["return"])
  end

  def back
    logger.info("params: #{params}")
    logger.info("raw post: #{request.raw_post}")
    payload = request.raw_post
    session_id = Nokogiri::XML(payload).xpath('//notify:SessionID', 'notify' => 'urn:mace:shibboleth:2.0:sp:notify').text.strip
    logger.debug session_id

    db_session = Session.where(shib_session: session_id)
    logger.debug db_session
    response_node = if db_session.empty?
                      "<notify:NG/>"
                    else
                      "<notify:OK/>"
                    end
    db_session.first.destroy unless db_session.empty?

    soap = Nokogiri::XML::Builder.new { |xml|
      xml['soap-env'].Envelope('xmlns:soap-env' => 'http://schemas.xmlsoap.org/soap/envelope/', 'xmlns:notify' => 'urn:mace:shibboleth:2.0:sp:notify') do
        xml['soap-env'].Body do
          xml['soap-env'].LogoutNotificationResponse do
            xml << response_node
          end
        end
      end
    }
    soap.to_xml

    logger.debug soap.to_xml
    render xml: soap, content_type: "text/xml"
  end

end

app/controllers/sso_controller.rb
class SsoController < ApplicationController
  def auth
    sso_data = SsoEnvTranslator.exec(request.env)

    session[:uid] = sso_data[:uid]
    session[:cn] = sso_data[:cn]
    shib_session = sso_data[:shib_session]

    logger.info("Shib-Session-ID as session is #{shib_session}")

    # session.id is cleartext
    logger.debug("session id: #{session.id}")

    private_id = Rack::Session::SessionId.new(session.id.to_s).private_id

    logger.debug("private_session: #{private_id}")

    db_session = Session.find_by_session_id(private_id)
    db_session.shib_session = shib_session
    db_session.save

    redirect_to :controller => 'main', :action => 'welcome'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/slo_helper.rb
module SloHelper
end

app/helpers/sso_helper.rb
module SsoHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Proper SSO
    = csrf_meta_tags
    = csp_meta_tag
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'fa', 'data-turbolinks-track': 'reload'
  %body.has-background-light
    %section.section.is-mobile
      .container.has-background-white{style: "padding: 1em;"}
        %h1.title My application
        = yield
        %hr
        %footer
          %p
            Just a standard footer

app/views/main/welcome.html.haml
- if @logged_in
  %p
    Welcome
    = @cn
  %p
    = button_to("Logout", "/Shibboleth.sso/Logout")
- else
  %p
    = button_to("Login with Shibboleth", sso_auth_path, method: :get)

app/views/slo/notify.html.haml
%h1 Slo#notify
%p Find me in app/views/slo/notify.html.haml

app/views/sso/auth.html.haml
%h1 Sso#auth
%p Find me in app/views/sso/auth.html.haml